# Generated by Django 3.0 on 2019-12-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckeckers_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=8)),
                ('first_player_checkers', models.CharField(default='1@1#2@2#', max_length=100)),
                ('second_player_checkers', models.CharField(default='1@1#2@2#', max_length=100)),
                ('turn', models.IntegerField(default=0)),
            ],
        ),
    ]
