# Generated by Django 3.0 on 2019-12-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckeckers_api', '0006_auto_20191220_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='first_player_username',
        ),
        migrations.RemoveField(
            model_name='game',
            name='second_player_username',
        ),
    ]
