# Generated by Django 3.0 on 2019-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckeckers_api', '0007_auto_20191220_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_player_username',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='second_player_username',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
